name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/package-lock.json
      - run: npm ci
      - run: npm test
      - name: Build (relative base)
        run: npm run build
        env:
          BASE_PATH: ./
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        game_slug: ["daadi"] # add more slugs here
    env:
      GAME_COLLECTION: _games
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: apps/dist
      - name: Derive version short SHA
        run: echo "VERSION_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Deploy versioned
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/dist
          destination_dir: ${{ env.GAME_COLLECTION }}/${{ matrix.game_slug }}/${{ env.VERSION_SHORT }}
          keep_files: true
      - name: Deploy latest alias
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/dist
          destination_dir: ${{ env.GAME_COLLECTION }}/${{ matrix.game_slug }}/latest
          keep_files: true

  publish-index:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      GAME_COLLECTION: _games
      GAME_SLUGS: "daadi" # space-separated list; keep in sync with matrix
    steps:
      - name: Generate root index
        run: |
          mkdir -p __ghpages_root
          cat > __ghpages_root/index.html <<'HTML'
          <!doctype html>
          <html>
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>LazySPA • Games</title>
              <style>
                body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,Helvetica Neue,Arial;line-height:1.5;margin:40px}
                h1{margin-bottom:16px;font-size:24px}
                ul{padding-left:20px}
                a{color:#2563eb;text-decoration:none}
                a:hover{text-decoration:underline}
                .muted{color:#6b7280;font-size:14px;margin-top:8px}
                code{background:#f1f5f9;padding:2px 4px;border-radius:4px}
              </style>
            </head>
            <body>
              <h1>Games</h1>
              <ul>
          HTML
          for slug in $GAME_SLUGS; do echo "                <li><a href=\"./$GAME_COLLECTION/$slug/latest/\">$slug</a></li>" >> __ghpages_root/index.html; done
          cat >> __ghpages_root/index.html <<'HTML'
              </ul>
              <div class="muted">Add more games by updating the workflow's matrix.</div>
            </body>
          </html>
          HTML
      - name: Publish root index
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: __ghpages_root
          keep_files: true
