name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/package-lock.json
      - run: npm ci
      - run: npm test
      - name: Build (relative base)
        run: npm run build
        env:
          BASE_PATH: ./
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        game_slug: ["daadi"] # add more slugs here
    env:
      GAME_COLLECTION: _games
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: apps/dist
      - name: Derive version short SHA
        run: echo "VERSION_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Deploy versioned
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/dist
          destination_dir: ${{ env.GAME_COLLECTION }}/${{ matrix.game_slug }}/${{ env.VERSION_SHORT }}
          keep_files: true
      - name: Deploy latest alias
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/dist
          destination_dir: ${{ env.GAME_COLLECTION }}/${{ matrix.game_slug }}/latest
          keep_files: true

  publish-manifest:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      GAME_COLLECTION: _games
      # Keep this in sync with deploy.strategy.matrix.game_slug
      GAME_SLUGS: "daadi"
      SITE_BASE: /lazyspa
    steps:
      - name: Derive version short SHA
        run: echo "VERSION_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Generate games.json
        run: |
          mkdir -p __gh_manifest
          {
            echo '{'
            echo '  "commit": "'${GITHUB_SHA}'",'
            echo '  "versionShort": "'${VERSION_SHORT}'",'
            echo '  "collection": "'${GAME_COLLECTION}'",'
            echo '  "games": ['
            first=1
            for slug in ${GAME_SLUGS}; do
              [ $first -eq 0 ] && echo ','
              echo '    {"slug":"'${slug}'","latest":"'${SITE_BASE}'/'${GAME_COLLECTION}'/'${slug}'/latest/"}'
              first=0
            done
            echo '  ]'
            echo '}'
          } > __gh_manifest/games.json
      - name: Publish games.json
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: __gh_manifest
          keep_files: true
  # Root index is now a tracked file on gh-pages, not generated by CI.
